# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Audiobookshelf"
version: "2.2.19"
slug: audiobookshelf
description: "Self-hosted audiobook and podcast server"
url: "https://github.com/advplyr/audiobookshelf"
arch:
  - aarch64
  - amd64
  - armv7
ports:
  - 13378/tcp: 13378
panel_icon: mid:book
ports_description:
  13378/tcp: "Audiobookshelf web interface"
image: "advplyr/audiobookshelf"
init: false
webui: "http://[HOST]:[PORT:13378]"
