# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Audiobookshelf"
version: "2.19.4"
slug: audiobookshelf
description: "Self-hosted audiobook and podcast server"
url: "https://github.com/advplyr/audiobookshelf"
arch:
  - aarch64
  - amd64
  - armv7
ports:
   80/tcp: 13378
panel_icon: mid:book
ports_description:
  80/tcp: "Audiobookshelf web interface"
init: false
webui: "http://[HOST]:[PORT:13378]"
map:
  - media:rw
  - share:rw
  - addon_config:rw
