# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Audiobookshelf
version: "0.1"
slug: audiobookshelf
description: Self-hosted audiobook and podcast server
url: "https://github.com/advplyr/audiobookshelf"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
ports:
  - 13378/tcp: 13378
image: "advplyr/audiobookshelf"
webui: "http://[HOST]:[PORT:13378]"
