# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "OpenAudible"
version: "latest"
slug: openaudible
description: "OpenAudible is a cross-platform audiobook manager designed for Audible users. Manage/Download all your audiobooks with this easy-to-use desktop application."
url: "https://openaudible.org/"
arch:
  - aarch64
  - amd64
  - armv7
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "OpenAudible webinterface"
panel_icon: mdi:headphones
init: false
image: hub.docker.com/openaudible/openaudible
webui: "http://[HOST]:[PORT:3000]"
