# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Storyteller"
version: "0.3.9 (2024-05-21)"
slug: storyteller
description: "Self-hosted platform for creating and reading ebooks with
synced narration"
url: "https://gitlab.com/smoores/storyteller"
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8001/tcp: 8001
ports_description:
  8001/tcp: "Storyteller web interface"
panel_icon: mdi:headphones
init: false
image: https://gitlab.com/smoores/storyteller
webui: "http://[HOST]:[PORT:8001]"